---
title: "Multilevel Regression and Poststratification Case Studies"
date: "2022-05-16"
author: "Juan Lopez-Martin, Justin H. Phillips, and Andrew Gelman"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    css: style.css
    config:
      toc:
        collapse: section
        before: |
          <li><a href="./">MRP Case Studies</a></li>
        after: |
          <li><a href="https://github.com/JuanLopezMartin/MRPCaseStudy" target="blank">Data and code</a></li>
      fontsettings:
        theme: white
        family: serif
        size: 1
      edit: https://github.com/JuanLopezMartin/MRPCaseStudy/edit/master/%s
      sharing:
        github: yes
        facebook: no
documentclass: book
bibliography: [book.bib, mrp.bib]
biblio-style: apalike
link-citations: yes
description: "Introduction to Bayesian Multilevel Modeling and Poststratification using rstanarm, brms, and Stan"
---

# Preface {-}

The following case studies intend to introduce users to Multilevel Modeling and Poststratification (MRP) and some of its extensions, providing reusable code and clear explanations. The first section^[The first section corresponds to a draft version of the introductory chapter to _Multilevel Regression and Poststratification: A Practical Guide and New Developments_, and oncoming book on the topic. This chapter has received additional contributions by Shiro Kuriwaki and Jonah Sol Gabry.] presents MRP, a statistical technique that allows to estimate subnational estimates from national surveys while adjusting for nonrepresentativeness. The second chapter extends MRP to overcome the limitation of only using variables included in the census. The last chapter develops a new approach that combines MRP with an ideal point model, allowing to obtain subnational estimates of latent attitudes based on multiple survey questions and improving the subnational estimates for an individual survey item based on other related items.

These case studies do not display some non-essential code, such as the ones used to generate figures and tables. However, all the code and data is available on the corresponding [GitHub repo](https://github.com/JuanLopezMartin/MRPCaseStudy).

The tutorials assume certain familiarity with R and Bayesian Statistics. A good reference to the required background is @gelman2020raos. Additionally, multilevel models are covered in @gelman2006data (Part 2A) or @mcelreath2020statistical (Chapters 12 and 13).

The case studies are still under development. Please send any feedback to [jl5522@columbia.edu](jl5522@columbia.edu).

